services:
#    monitor.example:
#        class: Fonasa\MonitorBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    fonasa_monitor.authentication.login_success_handler:
        class:  Fonasa\MonitorBundle\EventListener\LoginSuccessHandler
        arguments:  ["@router", "@security.authorization_checker"]
    fonasa_monitor.authentication.logout_handler:
        class:  Fonasa\MonitorBundle\EventListener\LogoutHandler
        arguments:  []