<?php

namespace Fonasa\MonitorBundle\Repository;

/**
 * AlcanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlcanceRepository extends \Doctrine\ORM\EntityRepository
{
}
