<?php

namespace Fonasa\MonitorBundle\Repository;

/**
 * HhRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HhRepository extends \Doctrine\ORM\EntityRepository
{
}
