<?php

namespace Fonasa\MonitorBundle\Repository;

/**
 * ImpactoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImpactoRepository extends \Doctrine\ORM\EntityRepository
{
}
