<?php

namespace Fonasa\MonitorBundle\Repository;

/**
 * OrigenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrigenRepository extends \Doctrine\ORM\EntityRepository
{
}
