<?php

namespace Fonasa\MonitorBundle\Repository;

/**
 * TareaUsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TareaUsuarioRepository extends \Doctrine\ORM\EntityRepository
{
}
