<?php

namespace Fonasa\MonitorBundle\Repository;

/**
 * TipoAlcanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoAlcanceRepository extends \Doctrine\ORM\EntityRepository
{
}
